const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,mocks={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{exports,require:n=>mocks[n]||require(n),setTimeout,clearTimeout,...globals});return exports}
const state=load('lib/client-state.ts',{}, {localStorage:{getItem:()=>'{broken'}});
test('malformed and incorrectly shaped browser storage falls back safely',()=>{assert.equal(state.readLocalList('x',state.validTeam).length,0);assert.equal(state.readLocalProfile({name:'',game:true}).game,true);const s=load('lib/client-state.ts',{}, {localStorage:{getItem:()=>'{"not":"an array"}'}});assert.equal(s.readLocalList('x',s.validTeam).length,0)});
test('database result errors reject instead of becoming success',async()=>{await assert.rejects(state.checked(Promise.resolve({error:new Error('denied')})),/denied/);assert.equal((await state.checked(Promise.resolve({data:[1],error:null}))).data[0],1)});
test('stalled work times out and rejects',async()=>{await assert.rejects(state.withTimeout(new Promise(()=>{}),5),/timed out/)});
function harness(file,client){let values=[],cursor=0,effects=[];const react={useState:v=>{let i=cursor++;if(!(i in values))values[i]=v;return [values[i],v=>values[i]=typeof v==='function'?v(values[i]):v]},useRef:v=>{let i=cursor++;return values[i]||(values[i]={current:v})},useEffect:fn=>{let i=cursor++;if(!values[i]){values[i]=true;effects.push(fn)}}};const jsx=(type,props)=>({type,props});const mod=load(file,{'react':react,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'fragment'},'@/lib/supabase':{getSupabase:()=>client},'@/lib/client-state':state,'@/lib/teams':{teams:[]},'next/link':{default:'a'}},{window:{dispatchEvent(){}},Event:class{},localStorage:{getItem:()=>'{bad'},setTimeout,clearTimeout});return {render(props={slug:'atlanta-falcons',id:'1',name:'Test'}){cursor=0;return mod.default(props)},async mount(){this.render();effects.splice(0).forEach(fn=>fn());await new Promise(r=>setTimeout(r,5))}}}
function nodes(tree,type){if(!tree||typeof tree!=='object')return [];if(Array.isArray(tree))return tree.flatMap(t=>nodes(t,type));return [...(tree.type===type?[tree]:[]),...nodes(tree.props?.children,type)]}
for(const file of ['FavoriteButton','SavedPlayerButton'])test(file+' preserves unsaved state on failure and permits retry',async()=>{let fail=true;const query={select(){return this},eq(){return this},maybeSingle:async()=>({data:null}),upsert:async()=>({error:fail?new Error('denied'):null})};const h=harness('components/'+file+'.tsx',{auth:{getSession:async()=>({data:{session:{user:{id:'u'}}}})},from:()=>query});await h.mount();let t=h.render();await nodes(t,'button')[0].props.onClick();t=h.render();assert.ok(nodes(t,'p')[0].props.children.includes('Could not save'));assert.ok(!nodes(t,'button')[0].props.className.includes('active'));fail=false;await nodes(t,'button')[0].props.onClick();t=h.render();assert.ok(nodes(t,'button')[0].props.className.includes('active'));assert.equal(nodes(t,'p').length,0)});
test('account session failure leaves loading state and offers working retry',async()=>{let fail=true;const h=harness('components/AccountCenter.tsx',{auth:{getSession:async()=>{if(fail)throw new Error('offline');return {data:{session:null}}},onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}});await h.mount();let t=h.render();assert.equal(nodes(t,'button')[0].props.children,'RETRY ACCOUNT');fail=false;nodes(t,'button')[0].props.onClick();await new Promise(r=>setTimeout(r,5));t=h.render();assert.ok(nodes(t,'button').some(b=>b.props.children==='SIGN IN'));assert.ok(!nodes(t,'button').some(b=>b.props.children==='RETRY ACCOUNT'))});
test('account preferences show progress, block duplicates, report failure and allow retry',async()=>{
 let fail=true, writes=0, release;
 const gate=new Promise(r=>release=r);
 const query={select(){return this},eq(){return this},maybeSingle(){return this},then(resolve){return Promise.resolve({data:[],count:0}).then(resolve)},async upsert(){writes++;await gate;return {error:fail?new Error('denied'):null}}};
 const h=harness('components/AccountCenter.tsx',{auth:{getSession:async()=>({data:{session:{user:{id:'u',email:'test@example.com'}}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},from:()=>query});
 await h.mount();let t=h.render();const save=nodes(t,'button').find(b=>b.props.children==='SAVE PREFERENCES');
 const pending=save.props.onClick();await save.props.onClick();t=h.render();assert.equal(writes,2);assert.ok(nodes(t,'button').find(b=>b.props.children==='SAVING…').props.disabled);
 assert.equal(nodes(t,'p').find(p=>p.props.role==='status').props.children,'Saving preferences…');
 release();await pending;t=h.render();assert.match(nodes(t,'p').find(p=>p.props.role==='status').props.children,/Could not save/);
 fail=false;await nodes(t,'button').find(b=>b.props.children==='SAVE PREFERENCES').props.onClick();t=h.render();assert.equal(nodes(t,'p').find(p=>p.props.role==='status').props.children,'Preferences saved to your account ✓');
});
