const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function setup({user={id:'u1',email:'owner@example.com',email_confirmed_at:'yes'},env={},providerStatus=200,throws=false}={}){
 const calls=[];const exports={};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/email/test/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Response,AbortSignal,Date,process:{env:{VERCEL_ENV:'production',NEXT_PUBLIC_SUPABASE_URL:'https://example.com',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'public',RESEND_API_KEY:'secret',RESEND_FROM_EMAIL:'FourthDown <alerts@updates.getfourthdown.com>',...env}},require:n=>n==='@supabase/supabase-js'?{createClient:()=>({auth:{getUser:async()=>({data:{user},error:null})}})}:{withTimeout:async p=>p},fetch:async(url,opts)=>{calls.push({url,...opts});if(throws)throw Error('network');return Response.json(providerStatus===200?{id:'email1'}:{message:'private provider detail'},{status:providerStatus})}});
 return {calls,post:(auth=true)=>exports.POST(new Request('https://getfourthdown.com/api/email/test',{method:'POST',headers:auth?{Authorization:'Bearer token'}:{},body:JSON.stringify({to:'attacker@example.com',subject:'injected'})}))};
}
test('test email rejects unauthenticated, unconfirmed, and preview sends',async()=>{for(const [opts,auth,status] of [[{},false,401],[{user:null},true,401],[{user:{id:'u',email:'x@example.com'}},true,403],[{env:{VERCEL_ENV:'preview'}},true,403]]){const h=setup(opts);assert.equal((await h.post(auth)).status,status);assert.equal(h.calls.length,0)}});
test('test email uses verified identity and fixed content; retries reuse provider key',async()=>{const h=setup();const r=await h.post();assert.equal(r.status,200);const d=await r.json();assert.match(d.message,/accepted for delivery/);await h.post();const payload=JSON.parse(h.calls[0].body);assert.deepEqual(payload.to,['owner@example.com']);assert.equal(payload.subject,'FourthDown: Test email');assert.equal(h.calls[0].headers['Idempotency-Key'],h.calls[1].headers['Idempotency-Key']);assert.equal(r.headers.get('Cache-Control'),'no-store')});
test('test mode and missing sender block production delivery checks',async()=>{for(const env of [{RESEND_TEST_RECIPIENT:'test@example.com'},{RESEND_FROM_EMAIL:''}]){const h=setup({env});assert.equal((await h.post()).status,503);assert.equal(h.calls.length,0)}});
test('provider rejection and network failure never report success or expose raw provider errors',async()=>{for(const opts of [{providerStatus:403},{throws:true}]){const h=setup(opts);const r=await h.post();assert.ok(r.status>=500);const d=await r.json();assert.equal(d.ok,false);assert.ok(!JSON.stringify(d).includes('private provider detail'))}});
