import {games as demoGames} from "@/lib/games";import {getLiveScoreboard} from "@/lib/live-nfl";import {notFound} from "next/navigation";import type {Metadata} from "next";
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const demo=demoGames.find(x=>x.id===id);if(demo)return {title:demo.away+" vs "+demo.home+" Game Center"};const live=await getLiveScoreboard();const g=live.games.find(x=>x.id===id);return {title:g?g.away+" vs "+g.home+" Game Center":"Game Center"}}
const rows=[["Total offense","—","—"],["Yards / play","—","—"],["Third down","—","—"],["Pressure rate","—","—"],["Turnover margin","—","—"]];
export default async function Game({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const demo=demoGames.find(x=>x.id===id);const live=demo?null:await getLiveScoreboard();const g:any=demo||live?.games.find(x=>x.id===id);if(!g)notFound();const isLive=g.source==="espn-public";
 return <section className="gamePage"><div className={isLive?"liveDataFlag":"demoFlag"}>{isLive?"LIVE PROTOTYPE GAME CENTER · Schedule and score data from the server-side feed.":"PROTOTYPE GAME CENTER · Demonstration data."}</div>
 <div className="scoreHero"><div className="club"><div className="bigBadge">{g.away}</div><h2>{g.awayName}</h2><small>{g.awayRecord||"—"} · AWAY</small>{g.awayScore!=null&&<strong className="heroScore">{g.awayScore}</strong>}</div>
 <div className="gameMeta"><span>{g.day} · {g.time}</span><h1>{g.away} <i>VS</i> {g.home}</h1><b>{g.venue}</b><small>{g.network}</small><p className="muted">{g.status}</p></div>
 <div className="club"><div className="bigBadge">{g.home}</div><h2>{g.homeName}</h2><small>{g.homeRecord||"—"} · HOME</small>{g.homeScore!=null&&<strong className="heroScore">{g.homeScore}</strong>}</div></div>
 <div className="gameContent"><main>{!isLive&&<section className="panel"><span className="kicker">FOURTHDOWN MODEL</span><h2>Win Probability</h2><div className="probRow"><b>{g.away} {g.probAway}%</b><div className="probTrack"><span style={{width:g.probAway+"%"}}></span></div><b>{g.home} {g.probHome}%</b></div></section>}
 <section className="panel"><h2>{isLive?"Live Game Snapshot":"Matchup Numbers"}</h2><table><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table><p className="muted">{isLive?"Advanced live stats plug into this panel next.":"Demo metrics shown until a licensed data provider is connected."}</p></section>
 <section className="panel"><h2>Scoring & Play-by-Play</h2><div className="timeline"><article><b>GAME FEED</b><p>{isLive?"Live event detail integration is the next V7.1 step.":"Drive and play events will appear here."}</p></article></div></section></main>
 <aside><section className="panel"><span className="kicker">MATCHUP EDGE</span><h2>What Matters</h2><p className="muted">Early-down efficiency · pressure · explosive plays</p></section><section className="panel"><span className="kicker">FANTASY SIGNAL</span><h2>Usage Watch</h2><p className="muted">Targets, carries, routes and red-zone opportunities.</p></section></aside></div></section>
}