import Link from "next/link";import FavoritesPanel from "@/components/FavoritesPanel";import {getLiveScoreboard,getLiveStandings} from "@/lib/live-nfl";import {GameCard} from "@/components/GameCard";
export const revalidate=60;
export default async function Home(){const [board,standings]=await Promise.all([getLiveScoreboard(),getLiveStandings()]);
 const seeds=(conf:string)=>standings.rows.filter(r=>r.conference.includes(conf)).sort((a,b)=>(parseFloat(b.pct)||0)-(parseFloat(a.pct)||0)||Number(b.wins)-Number(a.wins)).slice(0,7);
 return <><section className="hero v9Hero"><div><span className="kicker">FOURTHDOWN V9</span><h1>THE NFL.<br/><span className="red">IN ONE VIEW.</span></h1><p>Live scores, playoff race, player intelligence, injuries, analytics and fantasy context in one independent football dashboard.</p><div className="actions"><Link className="btn" href="/scores">LIVE GAME CENTER →</Link><Link className="btn secondary" href="/standings">PLAYOFF PICTURE</Link></div></div><div className="heroArt"><span className="heroPulse">LIVE</span><strong>32</strong><small>TEAMS · ONE DASHBOARD</small></div></section>
 {board.ok&&board.games.length>0&&<section className="page homeModule"><div className="sectionTitle"><div><span className="kicker">LIVE BOARD</span><h2>Games</h2></div><Link href="/scores">ALL GAMES →</Link></div><div className="gameGrid">{board.games.slice(0,4).map(g=><GameCard key={g.id} g={g}/>)}</div></section>}
 <FavoritesPanel/>
 {standings.ok&&<section className="page homeModule"><div className="sectionTitle"><div><span className="kicker">PLAYOFF RACE</span><h2>Current Seeds</h2></div><Link href="/standings">FULL STANDINGS →</Link></div><div className="seedGrid"><article className="panel"><h3>AFC</h3>{seeds("AFC").map((r,i)=><div className="seedRow" key={r.abbr}><b>{i+1}</b><span>{r.abbr} · {r.team}</span><strong>{r.wins}-{r.losses}</strong></div>)}</article><article className="panel"><h3>NFC</h3>{seeds("NFC").map((r,i)=><div className="seedRow" key={r.abbr}><b>{i+1}</b><span>{r.abbr} · {r.team}</span><strong>{r.wins}-{r.losses}</strong></div>)}</article></div></section>}
 <section className="page"><div className="grid"><Link className="card featureCard" href="/injuries"><span className="kicker">INJURY WATCH</span><h2>Availability</h2><p>Current player injury notes surfaced from active game and matchup feeds.</p></Link><Link className="card featureCard" href="/fantasy"><span className="kicker">FANTASY EDGE</span><h2>Leaders & Impact</h2><p>Player leaders, availability and matchup context for fantasy decisions.</p></Link><Link className="card featureCard" href="/analytics"><span className="kicker">DATA LAB</span><h2>Power Index</h2><p>Transparent record-based team strength signals with no black-box scoring.</p></Link></div></section></>}
